package com.example.offlinewallet;

import android.Manifest;
import android.app.AlertDialog;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.os.Build;
import android.os.Bundle;
import android.text.InputType;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Locale;

public class MainActivity extends AppCompatActivity {

    private static final int PERMISSION_REQUEST_CODE = 100;

    private KeyPair walletKeys;
    private BleGattServerManager gattServerManager;

    private TextView balanceText;
    private TextView statusText;
    private ListView historyListView;

    private WalletStore walletStore;
    private ArrayAdapter<String> historyAdapter;
    private final List<String> historyItems = new ArrayList<>();

    // Tracks the amount of the send currently in flight so the BLE success
    // callback knows how much to debit. Fine for a single-send-at-a-time demo;
    // would need to move onto the payload itself if sends can overlap.
    private double pendingSendAmount = 0;

    // Set once a QR scan for "Send Money" resolves, right before we kick off
    // the BLE scan-and-send. BleScanManager uses this to refuse to pay any
    // device other than the one whose QR was actually scanned.
    private byte[] pendingReceiverPublicKey = null;

    // Which of several QR flows the next camera scan is for — needed because
    // a single scanner launch is shared across the BLE-pairing flow and the
    // two-way no-Bluetooth payment flow.
    private enum ScanMode { SEND_LEGACY_BLE, RECEIVE_PAYMENT, CONFIRM_ACK }
    private ScanMode pendingScanMode = ScanMode.SEND_LEGACY_BLE;

    // The transaction most recently generated by "Pay via QR", kept around so
    // that once the payer scans the payee's ack QR, we can confirm the nonce
    // matches and know how much to actually debit.
    private QrPaymentUtil.TransactionData pendingOutgoingTx = null;
    private double pendingOutgoingAmountRupees = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        walletStore = new WalletStore(this);

        balanceText = findViewById(R.id.balanceText);
        statusText = findViewById(R.id.statusText);
        historyListView = findViewById(R.id.historyList);

        historyAdapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, historyItems);
        historyListView.setAdapter(historyAdapter);

        try {
            walletKeys = loadOrGenerateKeys();
        } catch (Exception e) {
            e.printStackTrace();
            statusText.setText("Key setup failed: " + e.getMessage());
        }

        refreshBalance();
        refreshHistory();
        trySyncPendingTransactions(); // attempt to flush any backlog from while we were offline

        requestBlePermissionsIfNeeded();

        findViewById(R.id.addMoneyButton).setOnClickListener(v -> showAddMoneyDialog());
        findViewById(R.id.receiveButton).setOnClickListener(v -> startAdvertising());
        findViewById(R.id.sendButton).setOnClickListener(v -> showSendAmountDialog());

        // New: QR-based receive (shows your public key as a QR) and
        // QR-based send (scans someone else's QR to identify + pay them).
        View receiveQrButton = findViewById(R.id.receiveQrButton);
        if (receiveQrButton != null) receiveQrButton.setOnClickListener(v -> showReceiveQrDialog());

        View scanQrButton = findViewById(R.id.scanQrButton);
        if (scanQrButton != null) scanQrButton.setOnClickListener(v -> {
            pendingScanMode = ScanMode.SEND_LEGACY_BLE;
            launchQrScanner();
        });

        // New: no-Bluetooth two-way QR payment flow.
        View payQrButton = findViewById(R.id.payQrButton);
        if (payQrButton != null) payQrButton.setOnClickListener(v -> showPayViaQrAmountDialog());

        View scanPaymentQrButton = findViewById(R.id.scanPaymentQrButton);
        if (scanPaymentQrButton != null) scanPaymentQrButton.setOnClickListener(v -> {
            pendingScanMode = ScanMode.RECEIVE_PAYMENT;
            launchQrScanner();
        });
    }

    private void refreshBalance() {
        balanceText.setText(formatAmount(walletStore.getBalance()));
    }

    private void refreshHistory() {
        historyItems.clear();
        historyItems.addAll(walletStore.getHistory());
        historyAdapter.notifyDataSetChanged();
    }

    private String formatAmount(double amount) {
        return String.format(Locale.getDefault(), "\u20B9%.2f", amount);
    }

    private double parseAmount(String text) {
        try {
            double amount = Double.parseDouble(text.trim());
            return amount;
        } catch (Exception e) {
            return -1;
        }
    }

    // ---------- QR: Receive (show your public key as a QR code) ----------

    private void showReceiveQrDialog() {
        try {
            String pubKeyB64 = Base64.getEncoder().encodeToString(walletKeys.getPublic().getEncoded());
            Bitmap qr = QrCodeUtil.generate(pubKeyB64, 600);

            ImageView imageView = new ImageView(this);
            imageView.setImageBitmap(qr);
            int pad = (int) (16 * getResources().getDisplayMetrics().density);
            imageView.setPadding(pad, pad, pad, pad);

            new AlertDialog.Builder(this)
                    .setTitle("Scan to pay me")
                    .setView(imageView)
                    .setPositiveButton("Done", null)
                    .show();
        } catch (Exception e) {
            Toast.makeText(this, "Couldn't generate QR: " + e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }

    // ---------- No-Bluetooth QR payment flow ----------

    // Step 1: payer enters an amount, we build a signed transaction and show it as a QR.
    private void showPayViaQrAmountDialog() {
        EditText input = new EditText(this);
        input.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
        input.setHint("Amount to pay");

        new AlertDialog.Builder(this)
                .setTitle("Pay via QR")
                .setMessage("Current balance: " + formatAmount(walletStore.getBalance()))
                .setView(input)
                .setPositiveButton("Generate QR", (dialog, which) -> {
                    double amount = parseAmount(input.getText().toString());
                    if (amount <= 0) {
                        Toast.makeText(this, "Enter a valid amount", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    if (amount > walletStore.getBalance()) {
                        Toast.makeText(this, "Insufficient balance", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    generateAndShowTransactionQr(amount);
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    private void generateAndShowTransactionQr(double amountRupees) {
        try {
            long amountPaise = Math.round(amountRupees * 100);
            String txJson = QrPaymentUtil.buildTransactionQr(walletKeys, amountPaise);

            // Keep the tx around so we can verify the ack's nonce matches it later.
            pendingOutgoingTx = QrPaymentUtil.parseAndVerifyTransaction(txJson);
            pendingOutgoingAmountRupees = amountRupees;

            Bitmap qr = QrCodeUtil.generate(txJson, 600);
            ImageView imageView = new ImageView(this);
            imageView.setImageBitmap(qr);
            int pad = (int) (16 * getResources().getDisplayMetrics().density);
            imageView.setPadding(pad, pad, pad, pad);

            new AlertDialog.Builder(this)
                    .setTitle("Show this to the payee")
                    .setMessage("After they scan it, tap below to scan their confirmation.")
                    .setView(imageView)
                    .setPositiveButton("Scan Confirmation", (d, w) -> {
                        pendingScanMode = ScanMode.CONFIRM_ACK;
                        launchQrScanner();
                    })
                    .setNegativeButton("Cancel", (d, w) -> {
                        pendingOutgoingTx = null; // don't leave a stale tx armed
                    })
                    .show();
        } catch (Exception e) {
            Toast.makeText(this, "Couldn't generate payment QR: " + e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }

    // Step 2: payee scanned a transaction QR — verify it, then ask for explicit
    // confirmation before crediting anything. Nothing changes the balance until
    // the user taps Accept.
    private void handleScannedTransaction(String scannedJson) {
        try {
            QrPaymentUtil.TransactionData tx = QrPaymentUtil.parseAndVerifyTransaction(scannedJson);
            double amountRupees = tx.amountPaise / 100.0;
            String senderKeyB64 = Base64.getEncoder().encodeToString(tx.senderPublicKey);
            String shortKey = senderKeyB64.length() > 16 ? senderKeyB64.substring(0, 16) + "\u2026" : senderKeyB64;

            new AlertDialog.Builder(this)
                    .setTitle("Confirm incoming payment")
                    .setMessage("Accept " + formatAmount(amountRupees) + " from " + shortKey + "?")
                    .setPositiveButton("Accept", (d, w) -> acceptScannedTransaction(tx, amountRupees, senderKeyB64))
                    .setNegativeButton("Reject", null)
                    .setCancelable(false)
                    .show();
        } catch (SecurityException e) {
            statusText.setText("Payment QR rejected: " + e.getMessage());
            Toast.makeText(this, "Invalid or tampered payment QR", Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            statusText.setText("Couldn't read payment QR: " + e.getMessage());
        }
    }

    // Only runs once the payee has explicitly tapped Accept in the dialog above.
    private void acceptScannedTransaction(QrPaymentUtil.TransactionData tx, double amountRupees, String senderKeyB64) {
        try {
            walletStore.credit(amountRupees);
            String counterparty = senderKeyB64.length() > 12 ? senderKeyB64.substring(0, 12) + "\u2026" : senderKeyB64;
            walletStore.addHistoryEntry("Received", amountRupees, counterparty);
            refreshBalance();
            refreshHistory();

            String ackJson = QrPaymentUtil.buildAckQr(walletKeys, tx);

            // Queue this transaction for server reporting once we're online.
            // Extract the ack signature we just generated so the report
            // carries proof from both sides.
            byte[] receiverSignature = Base64.getDecoder().decode(new JSONObject(ackJson).getString("signature"));
            walletStore.queuePendingSync(tx.senderPublicKey, walletKeys.getPublic().getEncoded(),
                    tx.amountPaise, tx.timestamp, tx.nonce, tx.signature, receiverSignature);
            trySyncPendingTransactions();

            Bitmap qr = QrCodeUtil.generate(ackJson, 600);
            ImageView imageView = new ImageView(this);
            imageView.setImageBitmap(qr);
            int pad = (int) (16 * getResources().getDisplayMetrics().density);
            imageView.setPadding(pad, pad, pad, pad);

            new AlertDialog.Builder(this)
                    .setTitle("Received " + formatAmount(amountRupees))
                    .setMessage("Show this confirmation QR back to the payer to complete the transfer.")
                    .setView(imageView)
                    .setPositiveButton("Done", null)
                    .show();
        } catch (Exception e) {
            statusText.setText("Couldn't finalize payment: " + e.getMessage());
        }
    }

    // Step 3: payer scanned the payee's ack QR — verify it, then ask for explicit
    // confirmation before debiting. Nothing changes the balance until Confirm is tapped.
    private void handleScannedAck(String scannedJson) {
        if (pendingOutgoingTx == null) {
            Toast.makeText(this, "No payment in progress to confirm", Toast.LENGTH_SHORT).show();
            return;
        }
        try {
            byte[] receiverPublicKey = QrPaymentUtil.parseAndVerifyAck(scannedJson, pendingOutgoingTx.nonce);
            byte[] receiverSignature = Base64.getDecoder().decode(new JSONObject(scannedJson).getString("signature"));
            String receiverKeyB64 = Base64.getEncoder().encodeToString(receiverPublicKey);
            String shortKey = receiverKeyB64.length() > 16 ? receiverKeyB64.substring(0, 16) + "\u2026" : receiverKeyB64;

            new AlertDialog.Builder(this)
                    .setTitle("Confirm payment sent")
                    .setMessage(shortKey + " confirmed receipt of " + formatAmount(pendingOutgoingAmountRupees)
                            + ". Finalize and debit your balance?")
                    .setPositiveButton("Confirm", (d, w) -> finalizeOutgoingPayment(receiverPublicKey, receiverSignature, receiverKeyB64))
                    .setNegativeButton("Cancel", (d, w) -> pendingOutgoingTx = null)
                    .setCancelable(false)
                    .show();
        } catch (SecurityException e) {
            statusText.setText("Confirmation rejected: " + e.getMessage());
            Toast.makeText(this, "That confirmation QR doesn't match this payment", Toast.LENGTH_LONG).show();
            pendingOutgoingTx = null;
        } catch (Exception e) {
            statusText.setText("Couldn't read confirmation QR: " + e.getMessage());
            pendingOutgoingTx = null;
        }
    }

    // Only runs once the payer has explicitly tapped Confirm in the dialog above.
    private void finalizeOutgoingPayment(byte[] receiverPublicKey, byte[] receiverSignature, String receiverKeyB64) {
        String counterparty = receiverKeyB64.length() > 12 ? receiverKeyB64.substring(0, 12) + "\u2026" : receiverKeyB64;
        walletStore.debit(pendingOutgoingAmountRupees);
        walletStore.addHistoryEntry("Sent", pendingOutgoingAmountRupees, counterparty);

        // Queue this transaction for server reporting once we're online.
        walletStore.queuePendingSync(pendingOutgoingTx.senderPublicKey, receiverPublicKey,
                pendingOutgoingTx.amountPaise, pendingOutgoingTx.timestamp, pendingOutgoingTx.nonce,
                pendingOutgoingTx.signature, receiverSignature);
        trySyncPendingTransactions();

        refreshBalance();
        refreshHistory();
        statusText.setText("Payment confirmed: " + formatAmount(pendingOutgoingAmountRupees));
        pendingOutgoingTx = null;
    }

    // Walks the queue of completed offline transactions and reports each to
    // /qrsync/report. Entries that succeed (RECORDED or DUPLICATE_IGNORED —
    // both mean the server has it accounted for) are removed; anything else
    // (network failure, server rejects it) stays queued to retry later.
    private void trySyncPendingTransactions() {
        new Thread(() -> {
            List<JSONObject> pending = walletStore.getPendingSync();
            int syncedCount = 0;
            for (JSONObject entry : pending) {
                try {
                    JSONObject result = postJson(SERVER_BASE_URL + "/qrsync/report", entry);
                    String status = result.optString("status", "");
                    if ("RECORDED".equals(status) || "DUPLICATE_IGNORED".equals(status)) {
                        walletStore.removePendingSync(entry.getString("nonce"));
                        syncedCount++;
                    }
                    // any other status (INVALID_*) stays queued — won't succeed on
                    // retry without new signatures, but we don't silently drop it
                } catch (Exception e) {
                    // network failure — leave this and remaining entries queued,
                    // we'll try again next time trySyncPendingTransactions() runs
                    break;
                }
            }
            int remaining = walletStore.getPendingSyncCount();
            if (syncedCount > 0 || remaining > 0) {
                int finalSynced = syncedCount;
                runOnUiThread(() -> {
                    if (finalSynced > 0) {
                        statusText.setText("Synced " + finalSynced + " transaction(s) with server"
                                + (remaining > 0 ? " \u2014 " + remaining + " still pending" : ""));
                    }
                });
            }
        }).start();
    }


    // ---------- QR: Send (scan someone else's QR to get their public key, for BLE) ----------

    private void launchQrScanner() {
        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setDesiredBarcodeFormats(java.util.Collections.singletonList("QR_CODE"));
        integrator.setPrompt("Scan the recipient's wallet QR code");
        integrator.setBeepEnabled(true);
        integrator.setOrientationLocked(true);
        integrator.initiateScan();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, android.content.Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result == null || result.getContents() == null) {
            super.onActivityResult(requestCode, resultCode, data);
            return;
        }

        String scanned = result.getContents().trim();

        switch (pendingScanMode) {
            case RECEIVE_PAYMENT:
                handleScannedTransaction(scanned);
                break;
            case CONFIRM_ACK:
                handleScannedAck(scanned);
                break;
            case SEND_LEGACY_BLE:
            default:
                handleScannedIdentityForBle(scanned);
                break;
        }
    }

    // Legacy BLE-pairing path: scanned QR content is just a Base64 public key.
    private void handleScannedIdentityForBle(String scannedPubKeyB64) {
        byte[] scannedKeyBytes;
        try {
            scannedKeyBytes = Base64.getDecoder().decode(scannedPubKeyB64);
            // Sanity check it's actually a usable Ed25519 X.509 key, not junk from
            // an unrelated QR code someone points the scanner at.
            KeyFactory.getInstance("Ed25519").generatePublic(new X509EncodedKeySpec(scannedKeyBytes));
        } catch (Exception e) {
            Toast.makeText(this, "That QR code isn't a valid wallet key", Toast.LENGTH_SHORT).show();
            return;
        }
        pendingReceiverPublicKey = scannedKeyBytes;
        showSendAmountDialogForQrRecipient();
    }

    private void showSendAmountDialogForQrRecipient() {
        EditText input = new EditText(this);
        input.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
        input.setHint("Amount to send");

        new AlertDialog.Builder(this)
                .setTitle("Send Money (scanned recipient)")
                .setMessage("Current balance: " + formatAmount(walletStore.getBalance()))
                .setView(input)
                .setPositiveButton("Connect & Send", (dialog, which) -> {
                    double amount = parseAmount(input.getText().toString());
                    if (amount <= 0) {
                        Toast.makeText(this, "Enter a valid amount", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    if (amount > walletStore.getBalance()) {
                        Toast.makeText(this, "Insufficient balance", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    pendingSendAmount = amount;
                    startScanAndSend(amount, pendingReceiverPublicKey);
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    // Server base URL. On a physical device this can't be "localhost" (that
    // means the phone itself) — point it at your machine's LAN IP while the
    // server and phone are on the same Wi-Fi, e.g. "http://192.168.1.23:8080".
    // On an emulator, 10.0.2.2 reaches your host machine's localhost.
    private static final String SERVER_BASE_URL = "http://192.168.137.1:8080";

    private void showAddMoneyDialog() {
        EditText input = new EditText(this);
        input.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
        input.setHint("Amount to add");

        new AlertDialog.Builder(this)
                .setTitle("Add Money")
                .setMessage("This request is signed and sent to the server for approval.")
                .setView(input)
                .setPositiveButton("Request Top-up", (dialog, which) -> {
                    double amount = parseAmount(input.getText().toString());
                    if (amount <= 0) {
                        Toast.makeText(this, "Enter a valid amount", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    requestTopUp(amount);
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    // Signs (publicKey + amount + timestamp) with the wallet's own private
    // key and posts it to the server. The server verifies that signature
    // before crediting anything — the local balance only updates once the
    // server confirms APPROVED (auto-approved under its limit, or after
    // /admin/topup/{id}/approve for larger amounts).
    private void requestTopUp(double amountRupees) {
        statusText.setText("Requesting top-up approval...");
        new Thread(() -> {
            try {
                long amountPaise = Math.round(amountRupees * 100);
                long timestamp = System.currentTimeMillis();
                byte[] pubKeyBytes = walletKeys.getPublic().getEncoded();

                java.nio.ByteBuffer buf = java.nio.ByteBuffer.allocate(pubKeyBytes.length + 8 + 8);
                buf.put(pubKeyBytes);
                buf.putLong(amountPaise);
                buf.putLong(timestamp);

                Signature signer = Signature.getInstance("Ed25519");
                signer.initSign(walletKeys.getPrivate());
                signer.update(buf.array());
                byte[] signature = signer.sign();

                JSONObject body = new JSONObject();
                body.put("publicKey", Base64.getEncoder().encodeToString(pubKeyBytes));
                body.put("amount", amountPaise);
                body.put("timestamp", timestamp);
                body.put("signature", Base64.getEncoder().encodeToString(signature));

                JSONObject result = postJson(SERVER_BASE_URL + "/topup/request", body);
                String status = result.optString("status", "UNKNOWN");
                String reason = result.optString("reason", "");
                String requestId = result.optString("requestId", "");

                if ("PENDING".equals(status)) {
                    runOnUiThread(() -> statusText.setText(
                            "Waiting for manual approval (id: " + requestId + ")..."));
                    pollForApproval(requestId, amountRupees);
                    return;
                }

                runOnUiThread(() -> {
                    if ("APPROVED".equals(status)) {
                        walletStore.credit(amountRupees);
                        walletStore.addHistoryEntry("Added money", amountRupees, "Top-up (server-approved)");
                        refreshBalance();
                        refreshHistory();
                        statusText.setText("Top-up approved: " + formatAmount(amountRupees));
                    } else {
                        statusText.setText("Top-up rejected: " + reason);
                    }
                });
            } catch (Exception e) {
                runOnUiThread(() -> statusText.setText("Top-up request failed: " + e.getMessage()));
            }
        }).start();
    }

    // Checks the server every few seconds to see whether an admin has
    // approved or rejected this request from the dashboard yet. Stops
    // after ~5 minutes if nobody actions it, or after too many consecutive
    // network failures in a row (a single dropped request no longer kills
    // the whole wait — only a run of them does).
    private void pollForApproval(String requestId, double amountRupees) {
        new Thread(() -> {
            int consecutiveFailures = 0;
            for (int attempt = 0; attempt < 100; attempt++) {
                try {
                    Thread.sleep(3000);

                    java.net.URL url = new java.net.URL(SERVER_BASE_URL + "/topup/" + requestId);
                    java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();
                    conn.setRequestMethod("GET");
                    conn.setConnectTimeout(10000);
                    conn.setReadTimeout(10000);

                    StringBuilder sb = new StringBuilder();
                    try (java.io.BufferedReader reader = new java.io.BufferedReader(
                            new java.io.InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
                        String line;
                        while ((line = reader.readLine()) != null) sb.append(line);
                    }
                    JSONObject result = new JSONObject(sb.toString());
                    String status = result.optString("status", "PENDING");
                    consecutiveFailures = 0; // this attempt succeeded

                    if ("APPROVED".equals(status)) {
                        runOnUiThread(() -> {
                            walletStore.credit(amountRupees);
                            walletStore.addHistoryEntry("Added money", amountRupees, "Top-up (server-approved)");
                            refreshBalance();
                            refreshHistory();
                            statusText.setText("Top-up approved: " + formatAmount(amountRupees));
                        });
                        return;
                    } else if ("REJECTED".equals(status)) {
                        String reason = result.optString("reason", "");
                        runOnUiThread(() -> statusText.setText("Top-up rejected: " + reason));
                        return;
                    }
                    // still PENDING — keep polling
                } catch (Exception e) {
                    consecutiveFailures++;
                    if (consecutiveFailures >= 5) {
                        runOnUiThread(() -> statusText.setText(
                                "Lost connection while waiting for approval \u2014 check server/network"));
                        return;
                    }
                    // transient failure — just try again on the next tick
                }
            }
            runOnUiThread(() -> statusText.setText("Top-up still pending \u2014 check back later"));
        }).start();
    }

    private JSONObject postJson(String urlStr, JSONObject body) throws Exception {
        java.net.URL url = new java.net.URL(urlStr);
        java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);
        conn.setConnectTimeout(10000);
        conn.setReadTimeout(10000);

        try (java.io.OutputStream os = conn.getOutputStream()) {
            os.write(body.toString().getBytes(StandardCharsets.UTF_8));
        }

        int code = conn.getResponseCode();
        java.io.InputStream is = code >= 200 && code < 300 ? conn.getInputStream() : conn.getErrorStream();
        StringBuilder sb = new StringBuilder();
        try (java.io.BufferedReader reader = new java.io.BufferedReader(
                new java.io.InputStreamReader(is, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) sb.append(line);
        }
        return new JSONObject(sb.toString());
    }

    private void showSendAmountDialog() {
        EditText input = new EditText(this);
        input.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
        input.setHint("Amount to send");

        new AlertDialog.Builder(this)
                .setTitle("Send Money")
                .setMessage("Current balance: " + formatAmount(walletStore.getBalance()))
                .setView(input)
                .setPositiveButton("Scan & Send", (dialog, which) -> {
                    double amount = parseAmount(input.getText().toString());
                    if (amount <= 0) {
                        Toast.makeText(this, "Enter a valid amount", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    if (amount > walletStore.getBalance()) {
                        Toast.makeText(this, "Insufficient balance", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    pendingSendAmount = amount;
                    // No QR scanned — legacy path, pays whichever device answers first.
                    startScanAndSend(amount, null);
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    // Android 12+ (API 31+) requires these granted at RUNTIME, not just
    // declared in the manifest — the app will crash on BLE calls without this.
    private void requestBlePermissionsIfNeeded() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            String[] permissions = {
                    Manifest.permission.BLUETOOTH_SCAN,
                    Manifest.permission.BLUETOOTH_ADVERTISE,
                    Manifest.permission.BLUETOOTH_CONNECT,
                    Manifest.permission.CAMERA
            };
            boolean allGranted = true;
            for (String p : permissions) {
                if (ContextCompat.checkSelfPermission(this, p) != PackageManager.PERMISSION_GRANTED) {
                    allGranted = false;
                    break;
                }
            }
            if (!allGranted) {
                ActivityCompat.requestPermissions(this, permissions, PERMISSION_REQUEST_CODE);
            }
        }
    }

    private void startAdvertising() {
        byte[] pubKeyBytes = walletKeys.getPublic().getEncoded();
        gattServerManager = new BleGattServerManager(this, pubKeyBytes, this::handleIncomingPayload);
        gattServerManager.startAdvertisingAndServing();
        statusText.setText("Advertising \u2014 waiting for incoming payment...");
    }

    private void handleIncomingPayload(byte[] data) {
        try {
            String json = new String(data, StandardCharsets.UTF_8);
            JSONObject obj = new JSONObject(json);
            double amount = obj.getDouble("amount");
            String senderKey = obj.optString("senderKey", "unknown");

            walletStore.credit(amount);
            String counterparty = senderKey.length() > 12 ? senderKey.substring(0, 12) + "\u2026" : senderKey;
            walletStore.addHistoryEntry("Received", amount, counterparty);

            runOnUiThread(() -> {
                refreshBalance();
                refreshHistory();
                statusText.setText("Received " + formatAmount(amount));
            });
        } catch (JSONException e) {
            runOnUiThread(() -> statusText.setText("Received malformed payment data"));
        }
    }

    // expectedReceiverPublicKey: non-null when the recipient was identified via
    // QR scan — BleScanManager will refuse to pay any device whose identity
    // characteristic doesn't match this key. Null preserves the old "pay
    // whichever nearby device answers first" behavior.
    private void startScanAndSend(double amount, byte[] expectedReceiverPublicKey) {
        byte[] payload;
        try {
            JSONObject obj = new JSONObject();
            obj.put("amount", amount);
            obj.put("senderKey", Base64.getEncoder().encodeToString(walletKeys.getPublic().getEncoded()));
            obj.put("ts", System.currentTimeMillis());
            payload = obj.toString().getBytes(StandardCharsets.UTF_8);
        } catch (JSONException e) {
            Toast.makeText(this, "Failed to prepare payment", Toast.LENGTH_SHORT).show();
            return;
        }

        BleScanManager scanManager = new BleScanManager(this, payload, expectedReceiverPublicKey,
                new BleScanManager.OnSendCompleteListener() {
            @Override
            public void onSendSuccess() {
                walletStore.debit(pendingSendAmount);
                walletStore.addHistoryEntry("Sent", pendingSendAmount, "Nearby device");
                runOnUiThread(() -> {
                    refreshBalance();
                    refreshHistory();
                    statusText.setText("Sent successfully!");
                });
            }

            @Override
            public void onSendFailed(String reason) {
                runOnUiThread(() -> statusText.setText("Send failed: " + reason));
            }
        });
        scanManager.startScan();
        statusText.setText(expectedReceiverPublicKey != null
                ? "Connecting to scanned recipient..."
                : "Scanning for nearby wallets...");
    }

    private KeyPair loadOrGenerateKeys() throws Exception {
        File privFile = new File(getFilesDir(), "wallet_private.key");
        File pubFile  = new File(getFilesDir(), "wallet_public.key");

        if (privFile.exists() && pubFile.exists()) {
            byte[] privBytes = Files.readAllBytes(privFile.toPath());
            byte[] pubBytes  = Files.readAllBytes(pubFile.toPath());
            KeyFactory kf = KeyFactory.getInstance("Ed25519");
            PrivateKey priv = kf.generatePrivate(new PKCS8EncodedKeySpec(privBytes));
            PublicKey pub   = kf.generatePublic(new X509EncodedKeySpec(pubBytes));
            return new KeyPair(pub, priv);
        } else {
            KeyPairGenerator kpg = KeyPairGenerator.getInstance("Ed25519");
            KeyPair pair = kpg.generateKeyPair();
            Files.write(privFile.toPath(), pair.getPrivate().getEncoded());
            Files.write(pubFile.toPath(), pair.getPublic().getEncoded());
            return pair;
        }
    }
}
